--- #YAML:1.0
name:               POE-Component-IRC-Plugin-Hello
version:            0.001
abstract:           PoCo-IRC plugin that says hello
author:
    - Marius Gavrilescu <marius@ieval.ro>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::MockObject:  1.09
requires:
    IRC::Utils:           0
    List::Util:           0
    perl:                 5.014
    POE::Component::IRC::Plugin:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
