---
abstract: 'PoCo-IRC plugin that says hello'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  Test::MockObject: '1.09'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-IRC-Plugin-Hello
no_index:
  directory:
    - t
    - inc
requires:
  IRC::Utils: '0'
  List::Util: '0'
  POE::Component::IRC::Plugin: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=poe-component-irc-plugin-hello.git
version: '0.001002'
